// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgettoPtco.Data;

#nullable disable

namespace ProgettoPtco.Migrations
{
    [DbContext(typeof(TemperatureDBContext))]
    partial class TemperatureDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ProgettoPtco.Data.Detection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("altitudine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idDevice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pressione")
                        .HasColumnType("INTEGER");

                    b.Property<int>("temperatura")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("umidita")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("detections");
                });
#pragma warning restore 612, 618
        }
    }
}
